### ISSUE TITLE
Issue test.py not running

### ISSUE THREAD

**Issue by ThomasPf** [VU-Programming/AP2-Skeleton#2]
Please fill in the following sections, thank you!
### Details

VUNet ID : tpn380
Assistant: Mike Spadaru
### Issue

When i try to run the program, it just says 
java < Python test.py at the top of terminal and doesn't do anything.
### Output

```
nothing, not even running
```

**Comment by BlackNovaTech** [comment]
What is the command you used to run the test?

**Comment by ThomasPf** [comment]
multiple, running from:
cd '/Users/Pfann/Desktop/AP2/' && '/usr/local/bin/python'  '/Users/Pfann/Desktop/AP2/test.py'  && echo Exit status: $? && exit 1

cd '/Users/Pfann/Desktop/AP2/' && '/usr/local/bin/pythonw'  '/Users/Pfann/Desktop/AP2/test.py'  && echo Exit status: $? && exit 1

Python test.py /Users/Pfann/Desktop/AP2/build/libs/AP2-1.0.jar 

or just Python test.py

**Comment by sirmc** [comment]
Can you check that python actually executes the script. Add a print to the top of the python file, and see if that one is printed.

If not, maybe you have a botched/ old Python installation? Try installing Python 2.7 using Homebrew: http://brew.sh.

**Comment by ThomasPf** [comment]
It prints the statement, so that doesn't seem the problem.

Thomass-MacBook-Pro:~ Pfann$ cd '/Users/Pfann/Desktop/AP2/' && '/usr/local/bin/python'  '/Users/Pfann/Desktop/AP2/test.py'  && echo Exit status: $? && exit 1
Hello World

**Comment by ThomasPf** [comment]
(After putting in a hello world print statement)

**Comment by sirmc** [comment]
Does the script actually terminate? I think that the problem is that if you execute your program, that it actually never terminates.
Create an empty file called `in.txt`
Then execute `java -jar build/libs/AP2-1.0.jar < in.txt`.
The program should terminate almost immediately. If that isn't the case, have a look at your main loop in your program.

**Comment by BlackNovaTech** [comment]
What is the output of the script with -vv added?

**Comment by ThomasPf** [comment]
after running `java -jar build/libs/AP2-1.0.jar < in.txt` it indeed terminates immediately.

the output of the script with -vv is 
`Thomass-MacBook-Pro:AP2 Pfann$ python test.py -vv`
`Hello World`
`[   INFO] Running command java -jar build/libs/AP2-1.0.jar`

**Comment by ThomasPf** [comment]
I'm sorry guys i solved the problem. It was indeed a never ending loop due to a too complicated implementation of copy and my comment handling.

**Comment by ThomasPf** [comment]
Thanks for the help everyone!
