### ISSUE TITLE
Identifier length

### ISSUE THREAD

**Issue by ThomasPf** [VU-Programming/AP2-Skeleton#3]
### Details

VUNet ID : tpn380
Assistant: Mike Spadaru
### Issue

Not really an issue, however there is a test that checks the identifier if it's too long, however the manual only states an identifier as:

identifier = letter { letter | number } ;
An identifier starts with a letter and only consists of letters and numbers.
Nothing there about it being too long or only consiting of so many elements
### Output

```
[   INFO] Matching `APException: No end of line found` for error `identifier too long`
[SUCCESS] Error match!
[   INFO] Matching `APException: No identifier by the identifier of: PieterHijma` for error `identifier too long`
```

**Comment by sirmc** [comment]
I think this is a left-over from previous years. This test should be removed.

**Comment by ThomasPf** [comment]
thank you, a load off my mind!
